[package]
name = "derpisync"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.23", features = ["blocking"] }
serde = { version = "1.0.224", features = ["derive"] }
serde_json = "1.0.145"
